//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from "typeorm";

@Entity("MicrosoftPowerBI")
export class MicrosoftPowerBIEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column("text",{nullable: true})
title: string;

@Column("text",{nullable: true})
description: string;

@Column("real",{nullable: true})
price: number;

@Column("integer",{nullable: true})
duration: number;

@Column("text",{nullable: true})
exercises: string;


}
